scss_files:
  - 'scss/**/*.scss'

linters:
  BorderZero:
    enabled: true
    convention: none
  Comment:
    enabled: true
    exclude:
      - scss/main.scss
  ChainedClasses:
    enabled: true
  Indentation:
    enabled: true
    character: tab
    width: 1
  PropertySortOrder:
    enabled: true
    order: concentric
